// Toolbar and window-control icons as 16-color pixel art. Each icon is a
// grid of palette letters ('.' is clear), turned into an inline SVG.

const PAL = {
  k: '#000000', w: '#ffffff', g: '#808080', l: '#c0c0c0', y: '#ffff00', o: '#808000',
  n: '#000080', b: '#0000ff', r: '#ff0000', R: '#800000', c: '#008080', t: '#00ffff',
  G: '#008000', e: '#00ff00', m: '#800080',
};

export const ICONS = {
  new: `
...kkkkkkkk.....
...kwwwwwwkk....
...kwwwwwwklk...
...kwwwwwwkllk..
...kwwwwwwkkkkk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kwwwwwwwwwwk.
...kkkkkkkkkkkk.
................`,
  open: `
................
................
..........kkk...
.........k...k.k
..............kk
.kkkk........kkk
kywyyk..........
kywywykkkkkkk...
kwywywywywywk...
kywykkkkkkkkkkk.
kwykoooooooooook
kykoooooooooook.
kwkooooooooook..
kkooooooooook...
kkkkkkkkkkkk....
................`,
  save: `
................
.kkkkkkkkkkkkkk.
.kgkwwwwwwwwkgk.
.kgkwwwwwwwwkgk.
.kgkwwwwwwwwkgk.
.kgkwwwwwwwwkgk.
.kgkwwwwwwwwkgk.
.kggkkkkkkkkggk.
.kggggggggggggk.
.kggkkkkkkkkggk.
.kggklllkkllkgk.
.kggklllkkllkgk.
.kggklllkkllkgk.
..kgkkkkkkkkkgk.
...kkkkkkkkkkkk.
................`,
  print: `
................
.....kkkkkkkk...
....kwwwwwwwk...
....kwkkkkkwk...
...kwwwwwwwk....
...kwkkkkwwk....
..kkkkkkkkkkkkk.
.kllllllllllllk.
.kllllllllllGGk.
.kllllllllllllk.
.kggggggggggggk.
.kgkkkkkkkkkkgk.
.kgwwwwwwwwwwgk.
.kkkkkkkkkkkkkk.
................
................`,
  cut: `
................
...k.......k....
...k.......k....
...kk.....kk....
....k.....k.....
....kk...kk.....
.....kk.kk......
......kgk.......
.......k........
.....nn.nn......
....n..n..nn....
...n...n...n....
...n...n...n....
...n..n.n..n....
....nn...nn.....
................`,
  copy: `
................
kkkkkkk.........
kwwwwwkk........
kwkkkwkwk.......
kwwwwwkkkk......
kwkkkkkwwk......
kwwwwkkkkkkk....
kwkkkkwwwwwkk...
kwwwwkwkkkwkwk..
kwkkkkwwwwwkkkk.
kwwwwkwkkkkkwwk.
kkkkkkwwwwwwwwk.
.....kwkkkkkkwk.
.....kwwwwwwwwk.
.....kkkkkkkkkk.
................`,
  paste: `
................
......kkkk......
..kkkkllllkkkk..
.kooklkkkklkook.
.koooookkooooook
.kooooooooooook.
.kooookkkkkkkkk.
.koooookwwwwwwkk
.koooookwkkkkwwk
.koooookwwwwwwwk
.koooookwkkkkkwk
.koooookwwwwwwwk
.koooookwkkkkkwk
..kkkkkkwwwwwwwk
........kkkkkkkk
................`,
  undo: `
................
................
................
....k...........
...kk...........
..knkkkkkkkk....
.knnnnnnnnnnkk..
..knkkkkkkkknnk.
...kk.......knnk
....k........knk
.............knk
............knnk
..........kknnk.
.........knnkk..
.........kkk....
................`,
  bold: `
................
................
................
...kkkkkkkkk....
....kkkk..kkk...
....kkkk..kkk...
....kkkk..kkk...
....kkkkkkkk....
....kkkk..kkkk..
....kkkk...kkk..
....kkkk...kkk..
....kkkk..kkkk..
...kkkkkkkkkk...
................
................
................`,
  italic: `
................
................
................
.......kkkkkk...
.........kk.....
.........kk.....
........kk......
........kk......
.......kk.......
.......kk.......
......kk........
......kk........
....kkkkkk......
................
................
................`,
  underline: `
................
................
...kkkk..kkkk...
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
....kk....kk....
.....kkkkkk.....
................
...kkkkkkkkkk...
................
................
................`,
  font: `
................
.kkkkkkk........
..kk...k........
..kk............
..kk..k.........
..kkkkk.........
..kk..k....n....
..kk......nnn...
..kk......nnn...
.kkkk....n.nnn..
.........n.nnn..
........nnnnnnn.
........n...nnn.
.......n.....nnn
......nnn...nnnn
................`,
  indent: `
................
.kkkkkkkkkkkkkk.
................
.n....kkkkkkkkk.
.nn.............
.nnn..kkkkkkkkk.
.nnnn...........
.nnn..kkkkkkkkk.
.nn.............
.n....kkkkkkkkk.
................
.kkkkkkkkkkkkkk.
................
.kkkkkkkkkkkkkk.
................
................`,
  bullets: `
................
................
.nn...kkkkkkkkk.
.nn.............
................
................
.nn...kkkkkkkkk.
.nn.............
................
................
.nn...kkkkkkkkk.
.nn.............
................
................
................
................`,
  table: `
................
.kkkkkkkkkkkkkk.
.knnnnnnnnnnnnk.
.kkkkkkkkkkkkkk.
.kwwwkwwwkwwwwk.
.kwwwkwwwkwwwwk.
.kkkkkkkkkkkkkk.
.kwwwkwwwkwwwwk.
.kwwwkwwwkwwwwk.
.kkkkkkkkkkkkkk.
.kwwwkwwwkwwwwk.
.kwwwkwwwkwwwwk.
.kkkkkkkkkkkkkk.
................
................
................`,
  figure: `
................
.kkkkkkkkkkkkkk.
.kttttttttttttk.
.kttttttyyttttk.
.ktttttyyyyttttk
.kttttttyyttttk.
.ktttGtttttttttk
.kttGGGtttttttk.
.ktGGGGGtttGttk.
.kGGGGGGGtGGGtk.
.kGGGGGGGGGGGGk.
.kGGGGGGGGGGGGk.
.kkkkkkkkkkkkkk.
................
................
................`,
  speller: `
................
..k...kkk....kk.
.k.k..k..k..k...
.kkk..kkk...k...
.k.k..k..k..k...
.k.k..kkk....kk.
................
.............GG.
............GG..
...GG......GG...
....GG....GG....
.....GG..GG.....
......GGGG......
.......GG.......
................
................`,
  reveal: `
................
................
.kkkkkkkkkkkkkk.
.kwwwwwwwwwwwwk.
.kwkkkwkkwkkkwk.
.kwwwwwwwwwwwwk.
.kkkkkkkkkkkkkk.
.kllllllllllllk.
.kgggglllllllrk.
.kgggglkkkllgrk.
.kgggglllllllrk.
.kllllllllllllk.
.kkkkkkkkkkkkkk.
................
................
................`,
  zoom: `
................
....kkkk........
..kkwwwwkk......
..kwwwwwwk......
.kwwwwwwwwk.....
.kwwwwwwwwk.....
.kwwwwwwwwk.....
.kwwwwwwwwk.....
..kwwwwwwk......
..kkwwwwkkk.....
....kkkk.kkk....
..........kkk...
...........kkk..
............kk..
................
................`,
  fullpage: `
................
..kkkkkkkkkk....
..kwwwwwwwwk....
..kwkkkkkkwk....
..kwwwwwwwwk....
..kwkkkkkkwk....
..kwwwwwwwwk....
..kwkkkkkkwk....
..kwwwwwwwwk....
..kwkkkkkkwk....
..kwwwwwwwwk....
..kwkkkkkkwk....
..kwwwwwwwwk....
..kkkkkkkkkk....
................
................`,
  justLeft: `
................
................
.kkkkkkkkkkkkk..
................
.kkkkkkkkk......
................
.kkkkkkkkkkkk...
................
.kkkkkkk........
................
.kkkkkkkkkkkkk..
................
.kkkkkkkkkk.....
................
................
................`,
  justCenter: `
................
................
.kkkkkkkkkkkkk..
................
...kkkkkkkkk....
................
..kkkkkkkkkkk...
................
....kkkkkkk.....
................
.kkkkkkkkkkkkk..
................
...kkkkkkkkk....
................
................
................`,
  justRight: `
................
................
.kkkkkkkkkkkkk..
................
.....kkkkkkkkk..
................
..kkkkkkkkkkkk..
................
......kkkkkkkk..
................
.kkkkkkkkkkkkk..
................
....kkkkkkkkkk..
................
................
................`,
  justFull: `
................
................
.kkkkkkkkkkkkk..
................
.kkkkkkkkkkkkk..
................
.kkkkkkkkkkkkk..
................
.kkkkkkkkkkkkk..
................
.kkkkkkkkkkkkk..
................
.kkkkkk.........
................
................
................`,
  spacing: `
................
.n..............
nnn.kkkkkkkkkkk.
.n..............
.n..............
.n..kkkkkkkkkkk.
.n..............
.n..............
nnn.kkkkkkkkkkk.
.n..............
................
................
................
................
................
................`,
  app: `
................................
..kkkkkkkkkkkkkkkkkkkkkkkk......
..kwwwwwwwwwwwwwwwwwwwwwwkk.....
..kwkkkkkkkkkkkkkkkkkkkkwkwk....
..kwwwwwwwwwwwwwwwwwwwwwkwwk....
..kwkkkkkkkkkkkkkkkkkwwwkkkkk...
..kwwwwwwwwwwwwwwwwwwwwwwwwwk...
..kwkkkkkkkkkkkkkkkkkkkkkkkwk...
..kwwwwwwwwwwwwwwwwwwwwwwwwwk...
..kwkkkkkkkkkkkkkkkkkkkkkkkwk...
..kwwwwwwwwwwwwwwwwwwwwwwwwwk...
..kwkkkkkkkkkkkkkkkkkwwwwwwwk...
..kwwwwwwwwwwwwwwwwwwwwwwwwwk...
..kwwwwwwwwwwwwwwwwwwwwwwwwwk...
..kwwwwwwwwwwwwwwwwwwwwwwwwwk...
..kwwwwwwwwwwwwwwwwwwwwnnnnnnnn.
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwnnn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kwwwwwwwwwwwwwwwwwwwwwwwwwkn..
..kkkkkkkkkkkkkkkkkkkkkkkkkkkn..
................................
................................
................................
................................`,
  // window controls (drawn on their own button faces)
  sysbox: `
.............
.............
.............
.............
.............
..kkkkkkkkk..
..kwwwwwwwkk.
..kkkkkkkkkk.
...kkkkkkkkk.
.............
.............
.............
.............`,
  docbox: `
.............
.............
.............
.............
.............
...kkkkkkkk..
...kwwwwwwkk.
...kkkkkkkkk.
....kkkkkkkk.
.............
.............
.............
.............`,
  min: `
.............
.............
.............
.............
.............
...kkkkkkk...
....kkkkk....
.....kkk.....
......k......
.............
.............
.............
.............`,
  max: `
.............
.............
.............
.............
......k......
.....kkk.....
....kkkkk....
...kkkkkkk...
.............
.............
.............
.............
.............`,
  restore: `
.............
.............
......k......
.....kkk.....
....kkkkk....
...kkkkkkk...
.............
...kkkkkkk...
....kkkkk....
.....kkk.....
......k......
.............
.............`,
  down: `
.......
.......
kkkkkkk
.kkkkk.
..kkk..
...k...
.......`,
  info: `
................................
............kkkkkkkk............
.........kkkwwwwwwwwkkk.........
.......kkwwwwwwwwwwwwwwkk.......
......kwwwwwwwwwwwwwwwwwwk......
.....kwwwwwwwwbbbbwwwwwwwwk.....
....kwwwwwwwwbbbbbbwwwwwwwwk....
...kwwwwwwwwwbbbbbbwwwwwwwwwk...
...kwwwwwwwwwwbbbbwwwwwwwwwwk...
..kwwwwwwwwwwwwwwwwwwwwwwwwwwk..
..kwwwwwwwwwwbbbbbbwwwwwwwwwwk..
..kwwwwwwwwwwwbbbbbwwwwwwwwwwk..
.kwwwwwwwwwwwwbbbbbwwwwwwwwwwwk.
.kwwwwwwwwwwwwbbbbbwwwwwwwwwwwk.
.kwwwwwwwwwwwwbbbbbwwwwwwwwwwwk.
.kwwwwwwwwwwwwbbbbbwwwwwwwwwwwk.
.kwwwwwwwwwwwwbbbbbwwwwwwwwwwwk.
.kwwwwwwwwwwwwbbbbbwwwwwwwwwwwk.
..kwwwwwwwwwwwbbbbbwwwwwwwwwwk..
..kwwwwwwwwwwwbbbbbwwwwwwwwwwk..
..kwwwwwwwwwwbbbbbbbwwwwwwwwwk..
...kwwwwwwwwwwwwwwwwwwwwwwwwk...
...kwwwwwwwwwwwwwwwwwwwwwwwwk...
....kwwwwwwwwwwwwwwwwwwwwwwk....
.....kkwwwwwwwwwwwwwwwwwwkk.....
.......kkkwwwwwwwwwwwwkkk.......
..........kkkwwwwwwkkk..........
.............kwwwwk.............
..............kwwk..............
...............kk...............
................................
................................`,
};

const cache = new Map();

// An <svg> string for an icon; gray: draw it disabled (embossed gray).
export function icon(name, { gray = false, scale = 1 } = {}) {
  const key = name + (gray ? ':g' : '') + ':' + scale;
  if (cache.has(key)) return cache.get(key);
  const rows = ICONS[name].replace(/^\n/, '').split('\n');
  const h = rows.length, w = Math.max(...rows.map((r) => r.length));
  let rects = '';
  rows.forEach((row, y) => {
    let x = 0;
    while (x < row.length) {
      const ch = row[x];
      let x2 = x + 1;
      while (x2 < row.length && row[x2] === ch) x2++;
      if (ch !== '.' && PAL[ch]) {
        if (gray) {
          // disabled: a white copy one pixel down-right under a gray one
          rects += `<rect x="${x + 1}" y="${y + 1}" width="${x2 - x}" height="1" fill="#fff"/>`;
        } else rects += `<rect x="${x}" y="${y}" width="${x2 - x}" height="1" fill="${PAL[ch]}"/>`;
      }
      x = x2;
    }
  });
  if (gray) {
    // second pass in gray on top, skipping light pixels so the shape reads
    rows.forEach((row, y) => {
      let x = 0;
      while (x < row.length) {
        const ch = row[x];
        let x2 = x + 1;
        while (x2 < row.length && row[x2] === ch) x2++;
        if (ch !== '.' && ch !== 'w' && ch !== 'l' && ch !== 'y' && ch !== 't') rects += `<rect x="${x}" y="${y}" width="${x2 - x}" height="1" fill="#808080"/>`;
        x = x2;
      }
    });
  }
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${w * scale}" height="${h * scale}" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges" aria-hidden="true">${rects}</svg>`;
  cache.set(key, svg);
  return svg;
}

export function iconUrl(name, opts) {
  return `url("data:image/svg+xml,${encodeURIComponent(icon(name, opts))}")`;
}
