// Print (Shift-F7): the Print menu, printing to PDF, and View Document.

import { App } from './app.js';
import { layout, lineAt } from '../core/layout.js';
import { print } from '../core/measure.js';
import { makePdf, pageOps, bytes } from '../core/pdf.js';
import { COLS } from './screen.js';

const P = App.prototype;

// A full-screen menu. Resolves with the chosen key (upper-cased) or null.
P.screenMenu = function (draw, keys, { exitKeys = ['F7', 'F1', 'Esc', 'Enter', ' ', '0'] } = {}) {
  return new Promise((resolve) => {
    const done = (v) => { this.pop(m); resolve(v); };
    const m = this.push({
      full: true,
      draw: (scr) => { draw(scr); },
      key: (k) => {
        const u = String(k).toUpperCase();
        if (keys.includes(u)) done(u);
        else if (exitKeys.includes(k)) done(null);
        return true;
      },
    });
  });
};

// Draw "Selection: 0" plus an optional note.
P.selectionLine = function (scr, def = '0') {
  if (this.msg) scr.put(23, 0, typeof this.msg === 'string' ? this.msg : '');
  const c = scr.put(24, 0, 'Selection: ');
  scr.put(24, c, def);
  scr.setCursor(24, c);
};

// "1 - Full Document" with the mnemonic letter bold.
export function item(scr, row, col, n, text, mn, value, vcol = 40) {
  let c = scr.put(row, col, `${n} - `);
  const at = mn ? text.indexOf(mn) : -1;
  [...text].forEach((ch, j) => { c = scr.put(row, c, ch, j === at ? 'mn' : ''); });
  if (value !== undefined) scr.put(row, vcol, String(value));
}

const PRINT_ITEMS = [
  ['1', 'Full Document', 'F'], ['2', 'Page', 'P'], ['3', 'Document on Disk', 'D'], ['4', 'Control Printer', 'C'],
  ['5', 'Multiple Pages', 'M'], ['6', 'View Document', 'V'], ['7', 'Initialize Printer', 'I'],
];

P.drawPrintMenu = function (scr) {
  scr.put(0, 0, 'Print', 'b');
  PRINT_ITEMS.forEach(([n, t, m], k) => item(scr, 2 + k, 5, n, t, m));
  scr.put(10, 0, 'Options', 'b');
  const opts = [
    ['S', 'Select Printer', 'e', 'PDF (Courier)'], ['B', 'Binding Offset', 'B', '0"'], ['N', 'Number of Copies', 'N', '1'],
    ['U', 'Multiple Copies Generated by', 'M', 'Program'], ['G', 'Graphics Quality', 'G', 'Medium'], ['T', 'Text Quality', 'T', 'High'],
  ];
  opts.forEach(([n, t, , v], k) => item(scr, 12 + k, 5, n, t, t[0], v, 42));
  this.selectionLine(scr);
};

P.print = function () {
  return this.run(async () => {
    for (;;) {
      const c = await this.screenMenu((scr) => this.drawPrintMenu(scr), ['1', '2', '3', '4', '5', '6', '7', 'F', 'P', 'D', 'C', 'M', 'V', 'I', 'S', 'B', 'N', 'U', 'G', 'T']);
      this.msg = null;
      if (c === null) return;
      if (c === '1' || c === 'F') { await this.printPdf(null); return; }
      if (c === '2' || c === 'P') { await this.printPdf('page'); return; }
      if (c === '6' || c === 'V') { await this.viewDocument(); continue; }
      this.msg = 'Not available in this version';
    }
  });
};

P.printLayout = function () {
  return layout(this.ed.items, { measure: print });
};

P.docBase = function () {
  return this.doc.path ? this.store.basename(this.doc.path).replace(/\.[^.]*$/, '') : 'DOCUMENT';
};

P.printPdf = async function (which) {
  const res = this.printLayout();
  let out = res;
  if (which === 'page') {
    const line = lineAt(res, this.ed.cursor);
    out = { ...res, pages: [res.pages[line.page]] };
  }
  const base = this.docBase();
  const pdf = makePdf(out, { title: this.doc.path ? this.displayName(this.doc.path) : base });
  this.lastPdf = pdf;
  if (this.client) {
    const path = `/Documents/${base}.pdf`;
    const ok = await this.ask(`Save PDF to ${path}? `, 'Y');
    if (ok === null) return;
    if (ok) {
      await this.store.write(path, pdf, 'application/pdf');
      this.message(`Printed to ${this.displayName(path)}`);
      return;
    }
  }
  download(pdf, `${base}.pdf`);
  this.message(`Printed to ${base}.pdf`);
};

function download(latin1, name) {
  const blob = new Blob([bytes(latin1)], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 10000);
}

// ---- View Document ------------------------------------------------------

const ZOOMS = { '1': '100%', '2': '200%', '3': 'Full Page', '4': 'Facing Pages' };

P.viewDocument = function () {
  const res = this.printLayout();
  const line = lineAt(res, this.ed.cursor);
  const v = { page: line.page, zoom: this.viewZoom || '3', scroll: 0 };
  const canvas = this.canvas;
  return new Promise((resolve) => {
    const done = () => { canvas.style.display = 'none'; this.pop(m); resolve(); };
    const m = this.push({
      full: true,
      draw: (scr) => {
        scr.clear('vbg');
        const row = 24;
        scr.fill(row, 0, COLS, ' ');
        let c = 0;
        for (const [n, t] of Object.entries(ZOOMS)) c = scr.put(row, c, `${n} ${t}  `);
        c = scr.put(row, c - 2, ': ');
        scr.put(row, c, v.zoom);
        scr.setCursor(row, c);
        const right = `Doc ${this.cur + 1} Pg ${res.pages[v.page].n}`;
        scr.put(row, COLS - 1 - right.length, right);
        canvas.style.display = 'block';
        drawPages(canvas, res, v, this.pixelScale ? this.pixelScale() : 1);
      },
      key: (k) => {
        const pages = res.pages.length;
        if (ZOOMS[k]) { v.zoom = k; v.scroll = 0; this.viewZoom = k; }
        else if (k === 'PgDn') { v.page = Math.min(pages - 1, v.page + (v.zoom === '4' ? 2 : 1)); v.scroll = 0; }
        else if (k === 'PgUp') { v.page = Math.max(0, v.page - (v.zoom === '4' ? 2 : 1)); v.scroll = 0; }
        else if (k === 'Down') v.scroll += 0.5;
        else if (k === 'Up') v.scroll = Math.max(0, v.scroll - 0.5);
        else if (k === 'Home') { v.page = 0; v.scroll = 0; }
        else if (k === 'End') { v.page = pages - 1; v.scroll = 0; }
        else if (['F7', 'F1', 'Esc', ' ', 'Enter'].includes(k)) done();
        return true;
      },
    });
  });
};

export const VIEW_W = 720;
export const VIEW_H = 384;

function drawPages(canvas, res, v, pxScale) {
  const dpr = (globalThis.devicePixelRatio || 1) * pxScale;
  canvas.width = Math.round(VIEW_W * dpr);
  canvas.height = Math.round(VIEW_H * dpr);
  const ctx = canvas.getContext('2d');
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.fillStyle = '#000';
  ctx.fillRect(0, 0, VIEW_W, VIEW_H);
  const first = res.pages[v.page];
  const facing = v.zoom === '4';
  const ppi = v.zoom === '1' ? 80 : v.zoom === '2' ? 160 : (VIEW_H - 16) / first.h;
  let shown = [first];
  if (facing) {
    // even pages on the left, odd on the right
    const left = first.n % 2 === 0 ? first : res.pages[v.page - 1];
    const right = first.n % 2 === 0 ? res.pages[v.page + 1] : first;
    shown = [left, right];
  }
  const totalW = shown.reduce((s, p) => s + (p ? p.w * ppi : first.w * ppi), 0) + (shown.length - 1) * 4;
  let x0 = Math.max(4, (VIEW_W - totalW) / 2);
  const maxScroll = Math.max(0, first.h - (VIEW_H - 16) / ppi);
  v.scroll = Math.min(v.scroll, maxScroll);
  const y0 = 8 - v.scroll * ppi;
  for (const p of shown) {
    if (!p) { x0 += first.w * ppi + 4; continue; }
    drawPage(ctx, p, x0, y0, ppi);
    x0 += p.w * ppi + 4;
  }
}

const CSS_FAMILY = {
  Courier: '"Courier New", Courier, monospace',
  Times: '"Times New Roman", Times, serif',
  Helvetica: 'Arial, Helvetica, sans-serif',
};

function drawPage(ctx, page, x0, y0, ppi) {
  ctx.fillStyle = '#fff';
  ctx.fillRect(x0, y0, page.w * ppi, page.h * ppi);
  ctx.textBaseline = 'alphabetic';
  for (const op of pageOps(page)) {
    if (op.kind === 'rule') {
      ctx.fillStyle = '#000';
      ctx.fillRect(x0 + op.x1 * ppi, y0 + op.y * ppi - Math.max(0.5, op.w * ppi) / 2, (op.x2 - op.x1) * ppi, Math.max(0.5, op.w * ppi));
      continue;
    }
    const bold = op.font & 1, ital = op.font & 2;
    const px = (op.pt / 72) * ppi;
    ctx.font = `${ital ? 'italic ' : ''}${bold ? 'bold ' : ''}${px}px ${CSS_FAMILY[op.family] || CSS_FAMILY.Courier}`;
    const x = x0 + op.x * ppi, y = y0 + op.y * ppi;
    if (op.attrs.includes('SHADW')) { ctx.fillStyle = '#999'; ctx.fillText(op.text, x + px * 0.06, y + px * 0.06); }
    ctx.fillStyle = op.attrs.includes('REDLN') ? '#c00' : '#000';
    if (op.attrs.includes('OUTLN')) { ctx.strokeStyle = '#000'; ctx.lineWidth = Math.max(0.5, px / 30); ctx.strokeText(op.text, x, y); }
    else ctx.fillText(op.text, x, y);
  }
}
